name: telegram message
on: push
jobs:
  alert_telegram:
    name: Alert Telegram
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message:  Thằng ${{ github.actor }} vừa ${{ github.event_name }} commit vào repo ${{ github.repository }} của ${{github.repository_owner}}, nhánh ${{ github.ref }}.
