name: telegram message
on: [push, pull_request]
jobs:
  alert_telegram:
    name: Alert Telegram
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send telegram arlet push
      if: github.event_name == 'push'
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Thằng ${{ github.pusher.name }} vừa ${{ github.event_name }} lên nhánh ${{ github.ref }}. Chi tiết ${{ github.event.compare }}
