name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: -593348120
        token: 1670734630:AAHev_YkqM2PEjv6QkIxIIkeAmT9NJZwpyM
        args: Thằng ${{ github.event.inputs.name }} vừa ${{ github.event_name }} ở ${{ github.event.inputs.home }}.
